[package]
name = "project"
version = "0.1.0"
authors = ["Krovspey Stepan <pit-rpg@yandex.ua>"]

[dependencies]
glutin = "*"
gl = "*"
rand = "*"
num-traits = "*"
specs = "0.11"
uuid = { version = "0.5", features = ["v4"] }
# features = ["secure-password", "civet", "prod"]
byteorder = "1"

[features]
prod = []
