[package]
name = "project"
version = "0.1.0"
authors = ["Krovspey Stepan <pit-rpg@yandex.ua>"]

[dependencies]
glutin = "0.19.0"
gl = "0.11.0"
rand = "0.6.5"
specs = "0.14.3"
image = "0.21.0"
uuid = { version = "0.7.2", features = ["v4"] }
byteorder = "1.3.1"
typer = "0.1.1"
obj = "0.9.0"
regex = "1.1.2"
lazy_static = "1.3.0"
rayon = "1.0.3"
gltf = "0.11.3"

[features]
prod = []
names = []

[profile.dev]
opt-level = 2