[package]
name = "project"
version = "0.1.0"
authors = ["Krovspey Stepan <pit-rpg@yandex.ua>"]

[dependencies]
glutin = "*"
gl = "*"
rand = "*"
num-traits = "*"
# lib_derive = { path = "lib_derive" }
uuid = { version = "0.5", features = ["v4"] }
