[package]
name = "project"
version = "0.1.0"
authors = ["Krovspey Stepan <pit-rpg@yandex.ua>"]

[dependencies]
glutin = "0.19.0"
gl = "0.11.0"
rand = "0.6.0"
specs = "0.14"
image = "0.20.1"
uuid = { version = "0.7.1", features = ["v4"] }
byteorder = "1.2.7"
typer = "0.1.0"


[features]
prod = []


[profile.dev]
opt-level = 2