[package]
name = "lib-resource-manager"
version = "0.1.0"
authors = ["Stepan Krovspei <shtefanrpg@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0.39"
serde = {version =  "1.0.92", features = ["derive"]}
clap = "2.33.0"
colored = "1.8.0"
